# Generated by Django 5.0.6 on 2024-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='tipo',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
