# Generated by Django 5.0.6 on 2024-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_casa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='casas/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='tipo',
            field=models.CharField(default='Casa', max_length=20),
        ),
    ]
