# Generated by Django 5.0.6 on 2024-06-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
