# Generated by Django 5.0.6 on 2024-06-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
