# Generated by Django 5.0.6 on 2024-07-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='Aun no se ha expecifiado el sexo', max_length=1),
        ),
    ]
