# Generated by Django 5.0.6 on 2024-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_datosuser_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='avatar',
            field=models.ImageField(blank=True, default='Sin avatar aún', null=True, upload_to='avatares'),
        ),
    ]
